In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import re
from collections import defaultdict

df = pd.read_csv("/content/drive/MyDrive/vassista22_code_switching_adalora_checkpoints_phase1/Correct_Root.csv")

In [16]:
def split_root_suffix(token):
    m = re.match(r'^([A-Za-z]+)(.*)$', token)
    if m:
        root = m.group(1)
        suffix = m.group(2)
        if suffix == "":
            suffix = "∅"
        return root, suffix
    return None, None

In [11]:
def build_map(sentence):
    mp = {}
    for tok in sentence.strip().split():
        root, suf = split_root_suffix(tok)
        if root:
            mp[root] = suf
    return mp

In [29]:
insertions = 0
deletions = 0
substitutions = 0
correct = 0
total_roots = 0

for _, row in df.iterrows():
    R = build_map(row["Reference_Text"])
    H = build_map(row["Generated_Text"])

    for w in R:
        sR = R.get(w, "∅")
        sH = H.get(w, "∅")
        total_roots += 1

        if sR == sH:
            correct += 1
        elif sR != "∅" and sH == "∅":
            deletions += 1
        elif sR == "∅" and sH != "∅":
            insertions += 1
        else:
            substitutions += 1

In [7]:
MSER = (insertions + deletions + substitutions) / total_roots

print("Total English roots:", total_roots)
print("Correct:", correct)
print("Insertions:", insertions)
print("Deletions:", deletions)
print("Substitutions:", substitutions)
print("MSER:", MSER)
print("Suffix Accuracy:", 1 - MSER)

Total English roots: 1844
Correct: 1777
Insertions: 13
Deletions: 27
Substitutions: 27
MSER: 0.03633405639913232
Suffix Accuracy: 0.9636659436008677

In [8]:
conf = defaultdict(lambda: defaultdict(int))

for _, row in df.iterrows():
    R = build_map(row["Reference_Text"])
    H = build_map(row["Generated_Text"])

    for w in R:
        sR = R.get(w, "∅")
        sH = H.get(w, "∅")
        conf[sR][sH] += 1

pd.DataFrame(conf).fillna(0).astype(int)

,∅,-ஆ,-ல,-க்கு,-ஐயும்,-ஓட,-வ,-அ,-ட,-ம்,...,-க்கான,'s,-வா,.,-வுக்கு,-ஆல,-ஆம்,-ட்ட,-ஆ?,-வும்
∅,1406,0,1,0,0,0,0,1,0,0,...,0,1,0,12,0,0,0,0,1,0
-ல,3,0,122,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐ,1,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கு,1,0,0,79,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
?,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஏ,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அ,1,2,0,0,0,0,2,29,2,0,...,0,0,0,0,0,0,0,0,0,0
-யை,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
",",1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஆ,0,80,0,0,0,0,0,7,0,0,...,0,0,0,0,0,0,0,0,1,0
-ஆ?,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐயும்,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓட,0,0,0,0,0,11,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-வ,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-உம்,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
-ம்,0,0,0,0,0,0,0,0,0,7,...,0,0,0,0,0,0,0,0,0,0
-னு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அனு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கும்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அம்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
't,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கான,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
's,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
-வா,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
-வுக்கு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
-ஆல,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
-ஆம்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
-ட,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
-வும்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

# Experiment 2

In [9]:
import pandas as pd
import re
from collections import defaultdict

df = pd.read_csv("/content/drive/MyDrive/vassista22_code_switching_adalora_checkpoints_phase1_experiment2/Correct_Root.csv")

In [13]:
MSER = (insertions + deletions + substitutions) / total_roots

print("Total English roots:", total_roots)
print("Correct:", correct)
print("Insertions:", insertions)
print("Deletions:", deletions)
print("Substitutions:", substitutions)
print("MSER:", MSER)
print("Suffix Accuracy:", 1 - MSER)

Total English roots: 1301
Correct: 1246
Insertions: 7
Deletions: 17
Substitutions: 31
MSER: 0.042275172943889314
Suffix Accuracy: 0.9577248270561107

In [14]:
conf = defaultdict(lambda: defaultdict(int))

for _, row in df.iterrows():
    R = build_map(row["Reference_Text"])
    H = build_map(row["Generated_Text"])

    for w in R:
        sR = R.get(w, "∅")
        sH = H.get(w, "∅")
        conf[sR][sH] += 1

pd.DataFrame(conf).fillna(0).astype(int)

,∅,-ஆ,-ல,-க்கு,-ஐயும்,-ஓட,-வ,-அ,-ட,-ம்,...,-ஏ,",",'t,-க்கான,-வா,-ஆல,.,-ஆம்,-ஆ?,-வும்
∅,993,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,9,0,0,0
-ஐ,1,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
",",1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ல,2,0,86,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அ,2,1,0,0,0,0,3,21,1,0,...,0,0,0,0,0,0,0,0,0,0
?,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஆ,0,55,0,0,0,0,0,7,0,0,...,0,0,0,0,1,0,0,0,1,0
-ஆ?,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஆc,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கு,0,0,0,53,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-டுக்கு,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐயும்,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓட,0,0,0,0,0,8,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓ,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
-உம்,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
-ம்,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
-னு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ன்னு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கும்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அம்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஏ,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
-ே,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
't,0,0,0,0,0,0,0,0,0,0,...,0,0,5,0,0,0,0,0,0,0
-க்கான,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
-ஆல,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
-ஆம்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

# Experiment 3

In [15]:
import pandas as pd
import re
from collections import defaultdict

df = pd.read_csv("/content/drive/MyDrive/vassista22_code_switching_adalora_checkpoints_phase1_experiment3/Correct_Root.csv")

In [18]:
MSER = (insertions + deletions + substitutions) / total_roots

print("Total English roots:", total_roots)
print("Correct:", correct)
print("Insertions:", insertions)
print("Deletions:", deletions)
print("Substitutions:", substitutions)
print("MSER:", MSER)
print("Suffix Accuracy:", 1 - MSER)

Total English roots: 1823
Correct: 1750
Insertions: 9
Deletions: 28
Substitutions: 36
MSER: 0.04004388370817334
Suffix Accuracy: 0.9599561162918266

In [19]:
conf = defaultdict(lambda: defaultdict(int))

for _, row in df.iterrows():
    R = build_map(row["Reference_Text"])
    H = build_map(row["Generated_Text"])

    for w in R:
        sR = R.get(w, "∅")
        sH = H.get(w, "∅")
        conf[sR][sH] += 1

pd.DataFrame(conf).fillna(0).astype(int)

,∅,-ஆ,-ல,-க்கு,-ஐயும்,-ஓட,-வ,-அ,-ட,-ம்,...,-க்கான,-வா,.,-வுக்கு,-ஆம்,-லாம்,-ட்ட,-வும்,'s,-ஆ?
∅,1380,0,1,0,0,0,0,1,0,0,...,0,0,14,0,0,0,0,0,0,0
-ல,3,0,125,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐ,1,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கு,1,0,0,80,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
?,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அ,1,2,0,0,0,0,2,30,1,0,...,0,0,0,0,0,0,0,0,0,0
-யை,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஆ,0,81,0,0,0,0,0,7,0,0,...,0,0,0,0,0,0,0,0,0,2
-ஆ?,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐயும்,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓட,0,0,0,0,0,9,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-வ,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-வை,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓ,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
-இட்ட,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
-உம்,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
-ம்,0,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
-னு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கும்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அம்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஏ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
't,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கான,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
-வா,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
-வுக்கு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
-ஆம்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
-லாம்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
-ட,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
-வும்,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
's,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

# Experiment 4

In [20]:
import pandas as pd
import re
from collections import defaultdict

df = pd.read_csv("/content/drive/MyDrive/vassista22_code_switching_adalora_checkpoints_phase1_experiment4/Correct_Root.csv")

In [22]:
MSER = (insertions + deletions + substitutions) / total_roots

print("Total English roots:", total_roots)
print("Correct:", correct)
print("Insertions:", insertions)
print("Deletions:", deletions)
print("Substitutions:", substitutions)
print("MSER:", MSER)
print("Suffix Accuracy:", 1 - MSER)

Total English roots: 774
Correct: 745
Insertions: 5
Deletions: 9
Substitutions: 15
MSER: 0.037467700258397935
Suffix Accuracy: 0.962532299741602

In [23]:
conf = defaultdict(lambda: defaultdict(int))

for _, row in df.iterrows():
    R = build_map(row["Reference_Text"])
    H = build_map(row["Generated_Text"])

    for w in R:
        sR = R.get(w, "∅")
        sH = H.get(w, "∅")
        conf[sR][sH] += 1

pd.DataFrame(conf).fillna(0).astype(int)

,∅,-ஆ,-ல,-க்கு,-ஐயும்,-ஓட,-வ,-அ,-ட,-ம்,...,-னு,",",-க்கும்,?,-ஏ,'t,-க்கான,-வா,.,-வுக்கு
∅,586,0,1,0,0,0,0,1,0,0,...,0,3,0,2,0,0,0,0,1,0
-ல,2,0,52,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐ,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கு,1,0,0,36,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
?,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஆ,0,32,0,0,0,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஆ?,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அ,0,1,0,0,0,0,0,7,1,0,...,0,0,0,0,0,0,0,0,0,0
-ஐயும்,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓட,0,0,0,0,0,6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-வ,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓ,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
-உம்,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
-ம்,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
-னு,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
-க்கும்,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
-ஏ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,5,0,0,0,0,0
't,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
-க்கான,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
-வா,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
-வுக்கு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

# Experiment 6

In [24]:
import pandas as pd
import re
from collections import defaultdict

df = pd.read_csv("/content/drive/MyDrive/vassista22_code_switching_adalora_checkpoints_phase1_experiment6/Correct_Root.csv")

In [26]:
MSER = (insertions + deletions + substitutions) / total_roots

print("Total English roots:", total_roots)
print("Correct:", correct)
print("Insertions:", insertions)
print("Deletions:", deletions)
print("Substitutions:", substitutions)
print("MSER:", MSER)
print("Suffix Accuracy:", 1 - MSER)

Total English roots: 770
Correct: 740
Insertions: 6
Deletions: 8
Substitutions: 16
MSER: 0.03896103896103896
Suffix Accuracy: 0.961038961038961

In [27]:
conf = defaultdict(lambda: defaultdict(int))

for _, row in df.iterrows():
    R = build_map(row["Reference_Text"])
    H = build_map(row["Generated_Text"])

    for w in R:
        sR = R.get(w, "∅")
        sH = H.get(w, "∅")
        conf[sR][sH] += 1

pd.DataFrame(conf).fillna(0).astype(int)

,∅,-ஆ,-ல,-க்கு,-ஐயும்,-ஓட,-வ,-அ,-ட,-ம்,...,-க்கும்,?,-ஏ,",",'t,-க்கான,'s,-வா,.,-வுக்கு
∅,574,0,1,0,0,0,0,0,0,0,...,0,2,0,2,0,0,0,0,1,0
-ல,3,0,56,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐ,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கு,1,0,0,38,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஏ,1,0,0,0,0,0,0,0,0,0,...,0,0,5,0,0,0,0,0,0,0
-ஆ,0,29,0,0,0,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஆ?,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-அ,0,1,0,0,0,0,0,7,1,0,...,0,0,0,0,0,0,0,0,0,0
-லாம்,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஐயும்,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓட,0,0,0,0,0,6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-வ,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-ஓ,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
-உம்,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
-ம்,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
-னு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-க்கும்,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
't,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
-க்கான,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
's,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
-வா,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,0,0
-வுக்கு,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

Warning: Total number of columns (23) exceeds max_columns (20) limiting to first (20) columns.

# Whisper

In [28]:
import pandas as pd
import re
from collections import defaultdict

df = pd.read_csv("/content/drive/MyDrive/Whisper_large_v3_code_switching_adalora_checkpoints_phase1/Correct_Root.csv")

In [30]:
MSER = (insertions + deletions + substitutions) / total_roots

print("Total English roots:", total_roots)
print("Correct:", correct)
print("Insertions:", insertions)
print("Deletions:", deletions)
print("Substitutions:", substitutions)
print("MSER:", MSER)
print("Suffix Accuracy:", 1 - MSER)

Total English roots: 197
Correct: 189
Insertions: 5
Deletions: 1
Substitutions: 2
MSER: 0.04060913705583756
Suffix Accuracy: 0.9593908629441624

In [31]:
conf = defaultdict(lambda: defaultdict(int))

for _, row in df.iterrows():
    R = build_map(row["Reference_Text"])
    H = build_map(row["Generated_Text"])

    for w in R:
        sR = R.get(w, "∅")
        sH = H.get(w, "∅")
        conf[sR][sH] += 1

pd.DataFrame(conf).fillna(0).astype(int)

         ∅  -ல  -க்கு  -அ  -னு  -ஆ  -ஐ  .
∅      145   0      0   0    0   0   0  1
?        1   0      0   0    0   0   0  0
-அ       1   0      0   4    0   1   0  0
.        1   0      0   0    0   0   0  2
,        1   0      0   0    0   0   0  0
-        1   0      0   0    0   0   0  0
-ல       0  19      0   0    0   0   0  0
-க்கு    0   0      8   0    0   0   0  0
-e       0   0      0   1    0   0   0  0
-னு      0   0      0   0    1   0   0  0
-ஆ       0   0      0   0    0   9   0  0
-ஐ       0   0      0   0    0   0   1  0